{
    "Capture": {
    },
    "CtrlSet": {
        "Fun": 0,
        "Mode": 0
    },
    "Exp": {
        "ExterExpEnable": 0,
        "ExterExpFun": 2,
        "ExterModuIndex": 1,
        "ExterParIndex": 0,
        "InterExpEnable": 0,
        "InterExpFun": 0,
        "InterExpSwitch": 0,
        "InterExpVolSwitch": 0,
        "InterModuIndex": 2,
        "InterParIndex": 5
    },
    "Merge": [
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        0,
        0,
        false,
        false
    ],
    "Others": {
        "BPM": 80,
        "Delaytime_1": 460,
        "Delaytime_2": 0,
        "FxAtime": 460,
        "FxBtime": 460,
        "LedColor": 0,
        "Volume": 50,
        "pVersion": "V1.0"
    },
    "effectChain": [
        0,
        1,
        2,
        3,
        4,
        5,
        9,
        10,
        6,
        7,
        8
    ],
    "effectModule": {
        "AMP": {
            "Data": {
                "Bass": 40,
                "Gain": 22,
                "Mid": 64,
                "Mst": 55,
                "Pres": 50,
                "Treble": 64
            },
            "Switch": 1,
            "Type": 7
        },
        "CAB": {
            "Data": {
                "Center": 10,
                "Distance": 20,
                "Level": 50,
                "Mic": 2,
                "Sync": 0,
                "Tube": 1
            },
            "Switch": 1,
            "Type": 5
        },
        "DELAY": {
            "Data": {
                "F.Back": 27,
                "Level": 40,
                "Sub D": 0,
                "Time": 460
            },
            "Switch": 0,
            "Type": 0
        },
        "DS/OD": {
            "Data": {
                "Gain": 0,
                "Tone": 50,
                "Volume": 100
            },
            "Switch": 1,
            "Type": 3
        },
        "EQ": {
            "Data": {
                "1.6KHz": 40,
                "100Hz": 36,
                "250Hz": 23,
                "4KHz": 72,
                "630Hz": 84,
                "Level": 50
            },
            "Switch": 1,
            "Type": 0
        },
        "FX LOOP": {
            "Data": {
                "Dry/Wet": 50,
                "Loop Mode": 0,
                "Return Level": 60,
                "Send Level": 60
            },
            "Switch": 0
        },
        "FXA": {
            "Data": {
                "Level": 65,
                "Peak": 40,
                "Position": 25,
                "Q": 90
            },
            "Switch": 0,
            "Type": 0
        },
        "FXB": {
            "Data": {
                "Depth": 55,
                "Level": 50,
                "Rate": 320
            },
            "Switch": 0,
            "Type": 0
        },
        "NS GATE": {
            "Data": {
                "Thres": 20
            },
            "Switch": 0,
            "Type": 0
        },
        "REVERB": {
            "Data": {
                "Decay": 50,
                "Level": 30,
                "Pre delay": 0,
                "Tone": 40
            },
            "Switch": 0,
            "Type": 0
        },
        "TONE CAP": {
            "Data": {
                "SourceSync": 0
            },
            "Switch": 0,
            "Type": 0
        }
    },
    "fileInfo": {
        "app": "GE250 Edit",
        "app_version": "V1.0.0",
        "copyright": "Shenzhen Mooer Audio Co., Ltd. (c) 2019. All rights reserved",
        "device": "MOOER GE250",
        "device_version": "V1.0.0",
        "name": "CSFIX2",
        "schema": "GE250 Preset"
    }
}
